### ISSUE TITLE
Carthage integration not working

### ISSUE THREAD

**Issue by EinPfundKaese** [techprimate/TPPDF#114] opened 2019-02-05 10:33 UTC
I wanted to add TPPDF via Carthage to my project, but it didn't work and I get following message:

```
> carthage update
*** Fetching TPPDF
*** Checking out TPPDF at "1.3.2"
*** xcodebuild output can be found in /var/folders/qv/p26c8nhn2s7cx0079pfvhs000000gn/T/carthage-xcodebuild.xsziMb.log
*** Skipped building TPPDF due to the error:
Dependency "TPPDF" has no shared framework schemes
```
Could you please have a look?

**Comment by techprimate-phil** [comment] 2019-02-05 10:36
Seems to be a duplicate of #98 in the previous release. Can you try the solution I described there please?

**Comment by techprimate-phil** [comment] 2019-03-13 09:16
Fixed in #1a5119

**Closed by techprimate-phil** 2019-03-13 09:16 UTC
