### ISSUE TITLE
Multiple Pagination in one document

### ISSUE THREAD

**Issue by AniruddhSinhRathod** [techprimate/TPPDF#159] opened 2019-08-30 12:35 UTC
I want to add total page Number in Header and current page number in Footer.
is it possible ? plz help

**Comment by philprime** [comment] 2020-01-07 14:59
Hi there,

this seems like a useful but big change to the project, as it would require multiple dynamic paging objects. Calculating the numbers shouldn't be too hard, but the frame calculations of each paging object, growing over time, can be tough.

I will mark this as an enhancement, asking for help.

**Comment by philprime** [comment] 2020-05-20 08:06
Closed as this is a duplicate of #105

**Closed by philprime** 2020-05-20 08:06 UTC
Labels: enhancement, help wanted
