### ISSUE TITLE
How do I fix the row height of the table?

### ISSUE THREAD

**Issue by CodeSales** [techprimate/TPPDF#309] opened 2022-11-24 02:24 UTC
I know that the column width can be divided equally, and I want to divide it equally.

**Comment by brendand** [comment] 2022-11-26 02:52
I think there's already code in one of the branches to do this, but it hasn't made it to master yet. Hopefully it can be merged soon.

**Comment by philprime** [comment] 2022-12-03 14:11
Closing this as a duplicate of #158.
We'll continue the discussion in that thread

**Closed by philprime** 2022-12-03 14:11 UTC
Labels: duplicate, enhancement
