### ISSUE TITLE
Table content cut off on new page

### ISSUE THREAD

**Issue by albanotmakolli** [techprimate/TPPDF#205] opened 2020-05-30 13:22 UTC
When the content of a cell spans to another page the text is cutoff on the first and then the rest of it is rendered on the second page.

**Comment by philprime** [comment] 2020-05-30 13:33
hi there, this is actually on purpose, this feature is inspired by Apple Pages.
Would you prefer a break instead?

**Comment by albanotmakolli** [comment] 2020-05-30 13:48
Yes, a break would work better in my case. How can I set it to break? Thank you

**Comment by philprime** [comment] 2020-05-30 14:03
as of now this is not built-in (anymore) as I didn't have a use-case in combination with merged cells.

So how should it work with merged cells, move all rows with cut off cells to a new page?
How would you solve the following edge case:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/30923007/83330272-2cdda380-a28e-11ea-9b13-82fe6218c85e.png">

This is the current sample in the "experiment" example, if you want to check it out yourself.

Also can you provide me an example for reproducing your use case, so I can use it as a reference?

**Comment by philprime** [comment] 2020-05-30 18:01
WIP is on branch [`feature/205-optional-table-cell-splicing`](https://github.com/techprimate/TPPDF/tree/feature/205-optional-table-cell-splicing)

**Comment by StefaniOSApps** [comment] 2020-07-02 22:41
I also noticed this problem. It seems some time to exist. In an earlier version 1.6.X this worked without problems. Here you can see how the table covers the footer right. The branch you described was used here.

![IMG_B84E6B01AAED-1](https://user-images.githubusercontent.com/29314643/86414905-a588b300-bcc5-11ea-9db6-cf9a9f334f6c.jpeg)

**Comment by philprime** [comment] 2020-07-03 11:01
@StefaniOSApps this is looks like a bug, so this needs to be investigated for sure, looks like the content height is not correct.

Let me give you an insight why I changed the table behavior in 2.X.X:

First I wanted merged cells, but therefore I wanted to provide a easier table access, which should also be more Swift(y). That's why I added the subscript mechanism for content/alignment management and also the `merge()` function.

Now merging cells is actually pretty straight forward:

- Cells are class instances and the table is a 2D-Array which holds either pointers to the cells or nil if empty
- When merging two cells, all values (for the given indicies) are set to the same instance.
- During calculations the algorithm finds adjacent cells and combines their frames.
- Now it iterates all calculated/merged cells, and filters them by page before rendering

Now I had one design issue to face: **How to deal with merged cells at the page end?**
Previously if a cell was too long for the page, the whole row was moved to the next page.

But now how should we handle the case when a single cell can span multiple rows? 
What if every cell in  the row has different spanning (see my previous image)?

As Apple Pages has always been a reference to me, I decided to "break" table cut off at page end, and duplicate the last cells and mask it away, just like Pages does. That's the behavior you can currently see.

We can adapt the algorithm as we desire, but the behavior should be determined before hand.
How would you solve this problem?

Anyway, thank you for starting this discussion!

**Comment by philprime** [comment] 2020-07-19 16:03
There is now a WIP and a PR #223 about this issue. 
I implemented the flag and it works for my test case.
I am now looking into #205, which is the same use case but with headers on every page.

**Comment by zhxf2012** [comment] 2020-08-16 01:49
The same case, @albanotmakolli @philprime . Maybe there can be a bool config for choose to add break or left to cut off. Only cut off with text content is strange for end users.

**Comment by icarus31** [comment] 2020-11-14 19:03
@philprime, I tried you feature/205 branch and it fixed my issue with cut table cell. Super!

When you say "I am now looking into #205, which is the same use case but with headers on every page.", do you mean you will also fix the issue where the table header on the second page hides the first table cells?

**Comment by philprime** [comment] 2020-12-05 13:00
I am releasing the current progress so we can have smaller iterations fixing the table implementation.

As mentioned in #246, table headers on every page are still struggling, but the cut-off should be disabled now

**Comment by philprime** [comment] 2020-12-05 19:22
Alright this has been merged and released in 2.3.2
If this error still occurs for you, please reopen, or if it differs create a new issue

**Closed by philprime** 2020-12-05 19:22 UTC
Labels: enhancement

**Comment by sharuk998** [comment] 2025-12-23 08:43
Issue Still Present in TPPDF 2.6.1

**Problem**
When using table.shouldSplitCellsOnPageBreak = true, TPPDF splits cell content at pixel boundaries rather than line boundaries. This causes text lines to be visually cut in half at page breaks - the top portion of a line appears at the bottom of one page, and the rest continues on the next page.

**Expected Behavior**
When a cell spans multiple pages, text should split cleanly between lines (after a newline character or at word-wrap boundaries), not through the middle of a line.

**Reproduction**
```
let table = PDFTable(rows: 2, columns: 2)
table.style = PDFTableStyleDefaults.simple
table.showHeadersOnEveryPage = true
table.shouldSplitCellsOnPageBreak = true
table.padding = 4
table.margin = 2

// Add content large enough to span multiple pages (~6000+ characters)
let longText = (1...500).map { "Line \($0): Some text content here.\n" }.joined()

let attributedText = NSAttributedString(
    string: longText,
    attributes: [
        .font: NSFont.systemFont(ofSize: 12),
        .paragraphStyle: {
            let style = NSMutableParagraphStyle()
            style.lineSpacing = 4
            style.paragraphSpacing = 6
            return style
        }()
    ]
)

table[1, 0].content = try? PDFTableContent(content: attributedText)
document.add(table: table)
```

**Environment**
TPPDF version: 2.6.1 (latest)
Xcode: 16.2
Swift: 5
Platform: macOS

here's generated PDF [long leg cell.pdf](https://github.com/user-attachments/files/24307120/long.leg.cell.pdf)

**Comment by philprime** [comment] 2025-12-23 09:45
And what happens if you set `shouldSplitCellsOnPageBreak` to `false`? Is it moving the entire cell to the next page as expected?
