### ISSUE TITLE
no shared framework schemes

### ISSUE THREAD

**Issue by reinhardjung** [Techprimate/TPPDF#98] opened 2018-10-25 17:43 UTC
Hi

I'm new to this and i got an Error, which i think a had somewhen before.
Could you please help me and fix this?
ERROR:
*** Skipped building TPPDF due to the error:
Dependency "TPPDF" has no shared framework schemes for any of the platforms: iOS
If you believe this to be an error, please file an issue with the maintainers at https://github.com/Techprimate/TPPDF/issues/new

THANX A LOT!!!!!
  Reinhard

**Comment by marbetschar** [comment] 2018-11-11 13:55
When the following Carthage command is executed...

```
$ carthage bootstrap --platform iOS
```

... within a project containing the following line in the `Cartfile` ...

```
github "Techprimate/TPPDF" ~> 1.1
```

... the following error is thrown:

```
*** Skipped building TPPDF due to the error:
Dependency "TPPDF" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Techprimate/TPPDF/issues/new
```

Any suggestions how to fix?

**Comment by marbetschar** [comment] 2018-11-11 13:57
FWIW: When I execute `$ carthage update TPPDF` the following error is thrown:

```
*** Skipped building TPPDF due to the error:
Dependency "TPPDF" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Techprimate/TPPDF/issues/new
```

Please advise.

**Comment by marbetschar** [comment] 2018-11-12 13:37
@techprimate-phil don't know if we are on the same page here. To resolve the issue the suggested change should be done in the official TPPDF project and a new release should be created.

Is that what you are going to make and your suggestion is just a temporary workaround?

**Comment by techprimate-phil** [comment] 2018-11-12 13:42
Yes, there is going to be an official release, tough I am not able to inspect this issue right now, therefore I just wanted to provide a possible solution. 

Would be great if you could take a look if this is a valid solution and even better create a Pull Request

**Comment by marbetschar** [comment] 2018-11-13 17:21
Same here. Schemes are all checked as "Shared", but `Carthage` is still complaining it can't find a shared framework scheme. Don't know what the root cause of this issue is.

I'd love to provide a pull request, but unfortunately I don't have any idea where to start. Thoughts?

FWIW: I'm using Xcode v10.1 on macOS Mojave v10.14.1. It works on my old MacBook, but refuses to work on a brand new MacBook environment where I try to setup the exact same existing project.

**Comment by marbetschar** [comment] 2018-11-13 19:07
Tried to digg into this a bit deeper .... and failed. Created an issue @Carthage issue tracker. Hoping they can give further insights.

**Comment by techprimate-phil** [comment] 2018-11-13 19:23
I found something I need you to confirm: Please open *Example/Pods/Pods.xcodeproj* directly, unselect *Shared* for TPPDF in Schemes, and select it again. Then try ```carthage build --no-skip-current```

A Xcode scheme is saved in the folder inside of the ```.xcodeproj/xcshareddata/xcschemes``` folder and git tells me *Use -f if you really want to add them.* because they are in the .gitignore file.

If this fixes the issue, I can add the folder content to git and it should be fine.

→ Please confirm!

**Comment by marbetschar** [comment] 2018-11-13 19:30
Did as suggested ..... and party is on! 🎉🎉🎉

```
$ carthage build --no-skip-current
*** xcodebuild output can be found in /var/folders/w8/zwmgcwcn713d13s21t9wjwxm0000gp/T/carthage-xcodebuild.v6lwyY.log
*** Building scheme "TPPDF" in TPPDF.xcworkspace
$ 
```

no error is thrown; seems like this fixes the issue.

**Comment by techprimate-phil** [comment] 2018-11-13 19:33
Further investigation shows:

- `Pods.xcodeproj` does not contain  `xcshareddata/xcschemes/TPPDF.xcscheme` at checkout.
- XCode shows a invalid checkmark at `Shared` even if no scheme is shared.
- git includes the `Pod.xcodeproj` folder but excluded the *.xcscheme

→ Going to create a hotfix, adding the scheme

**Comment by techprimate-phil** [comment] 2018-11-13 19:49
Can anybody please try out 1.3.1 and let me know if the issue is resolved?

**Comment by marbetschar** [comment] 2018-11-13 19:59
Works perfectly. Thank you so much!

´´´
$ carthage update TPPDF
*** Checking out TPPDF at "1.3.1"
*** xcodebuild output can be found in /var/folders/w8/zwmgcwcn713d13s21t9wjwxm0000gp/T/carthage-xcodebuild.QXBTO2.log
*** Building scheme "TPPDF" in TPPDF.xcworkspace
´´´

Going to close the issue over @Carthage.

**Closed** 2018-11-13 20:00 UTC
Labels: bug, pending
