### ISSUE TITLE
Dotted lines 

### ISSUE THREAD

**Issue by raphdaff** [Techprimate/TPPDF#99] opened 2018-11-17 17:39 UTC
Hi there,

.. how do I get rid of those red or blue dotted lines around textElements, at margins etc in the generated file?

thx

**Comment by raphdaff** [comment] 2018-11-17 23:53
..sry. silly question. it is the debug mode:

   url = try PDFGenerator.generateURL(document: document, filename: "Example.pdf", progress: {
                (progressValue: CGFloat) in
                print("progress: ", progressValue)
            }, debug: false)

thx anyway.

**Comment by techprimate-phil** [comment] 2018-11-18 17:38
Duplicate of #83

**Closed** 2018-11-18 17:38 UTC
Labels: duplicate
