### ISSUE TITLE
Strikethrough does not work in table cell

### ISSUE THREAD

**Issue by marbetschar** [Techprimate/TPPDF#70] opened 2018-05-20 16:42 UTC
I have the following code, which should strike through the text on the first line - but it does not work. That said, it outputs all the text - but without striking through first line. How to fix?

```
let defaultNetSubTotal = "12456.34"
let customNetSubTotal = "-10%\n11210.706"

let contentString = NSMutableAttributedString()
contentString.append(NSMutableAttributedString(
	string: defaultNetSubTotal,
	attributes: [
		.baselineOffset: 0,
		.strikethroughStyle: NSUnderlineStyle.patternSolid.rawValue,
		.strikethroughColor: UIColor.black
	]
))

let paragraphStyle = NSMutableParagraphStyle()
paragraphStyle.alignment = .right
contentString.append(NSAttributedString(string: "\n" + customNetSubTotal, attributes: [
	.paragraphStyle: paragraphStyle
]))

columnCell.content = try PDFTableContent(content: contentString)
```

**Comment by marbetschar** [comment] 2018-06-29 08:47
how to fix this?

**Comment by techprimate-phil** [comment] 2018-06-29 17:32
Hi, as attributed strings are drawn the same way as a normal text element, this is a duplicate of #61

**Closed by techprimate-phil** 2018-06-29 17:32 UTC
